"""ProjektMigrationX1

Revision ID: 7e3982e99fa4
Revises: 
Create Date: 2026-09-30 15:40:11.738071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3982e99fa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=4), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('is_active IS TRUE'))
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='chk_warehouses_capacity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=4), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_number', sa.String(length=30), nullable=False),
    sa.Column('size', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'booked'"), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pickup_courier_id', sa.Integer(), nullable=True),
    sa.Column('delivery_courier_id', sa.Integer(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_window_start', sa.Time(), nullable=False),
    sa.Column('pickup_window_end', sa.Time(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_window_start', sa.Time(), nullable=True),
    sa.Column('delivery_window_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('warehouse_arrived_at', sa.DateTime(), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(delivery_date IS NULL AND delivery_window_start IS NULL AND delivery_window_end IS NULL) OR (delivery_date IS NOT NULL AND delivery_window_start IS NOT NULL AND delivery_window_end IS NOT NULL AND delivery_window_start < delivery_window_end)', name='chk_parcels_delivery_window'),
    sa.CheckConstraint('delivered_at IS NULL OR (out_for_delivery_at IS NOT NULL AND delivered_at >= out_for_delivery_at)', name='chk_parcels_delivered_order'),
    sa.CheckConstraint('delivery_courier_id IS NULL OR delivery_date IS NOT NULL', name='chk_parcels_delivery_courier_assigned'),
    sa.CheckConstraint('delivery_date IS NULL OR delivery_date >= pickup_date', name='chk_parcels_delivery_after_pickup'),
    sa.CheckConstraint('out_for_delivery_at IS NULL OR (warehouse_arrived_at IS NOT NULL AND out_for_delivery_at >= warehouse_arrived_at)', name='chk_parcels_out_delivery_order'),
    sa.CheckConstraint('picked_up_at IS NULL OR picked_up_at >= created_at', name='chk_parcels_picked_up_order'),
    sa.CheckConstraint('pickup_window_start < pickup_window_end', name='chk_parcels_pickup_window'),
    sa.CheckConstraint('sender_id <> recipient_id', name='chk_parcels_sender_recipient_diff'),
    sa.CheckConstraint('warehouse_arrived_at IS NULL OR (picked_up_at IS NOT NULL AND warehouse_arrived_at >= picked_up_at)', name='chk_parcels_warehouse_order'),
    sa.ForeignKeyConstraint(['delivery_courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_id'),
    sa.UniqueConstraint('sender_id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index('idx_parcels_delivery_courier', 'parcels', ['delivery_courier_id', 'delivered_at'], unique=False)
    op.create_index('idx_parcels_pickup_courier', 'parcels', ['pickup_courier_id', 'picked_up_at'], unique=False)
    op.create_index(op.f('ix_parcels_delivery_date'), 'parcels', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_parcels_status'), 'parcels', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_status'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_delivery_date'), table_name='parcels')
    op.drop_index('idx_parcels_pickup_courier', table_name='parcels')
    op.drop_index('idx_parcels_delivery_courier', table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('warehouses')
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('is_active IS TRUE'))
    op.drop_table('users')
    # ### end Alembic commands ###
